# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'mic' to control your mic input level (uses the default recording device)
# you can use 'deej.unmapped' to control all apps that aren't bound to any slider (this ignores master, system, mic and device-targeting sessions)
# windows only - you can use 'deej.current' to control the currently active app (whether full-screen or not)
# windows only - you can use a device's full name, i.e. "Speakers (Realtek High Definition Audio)", to bind it. this works for both output and input devices
# windows only - you can use 'system' to control the "system sounds" volume
# important: slider indexes start at 0, regardless of which analog pins you're using!
slider_mapping:
  0: master
  1: 
    - chrome.exe
    - brave.exe
  2: deej.unmapped
  3: discord.exe


# For keyboard button mapping (A button presses a key):
  # supported button list https://github.com/micmonay/keybd_event/blob/master/keybd_windows.go (scroll down)
  # be sure to convert hex values to decimal (hex values start with 0x)
  # for example: to get F13 (0x7C + 0xFFF)
  # 0x7C  = 124
  # 0xFFF = 4095
  # 124 + 4095
  # F13 = 4219
# For script button mapping (A button runs a script):
  # for each item have type: script
  # and value: '{LOCATION OF SCRIPT}'
  # Supported script types:
  # Windows [.bat, .ps1, .exe] Linus/Mac [.sh (and chmod +x must be set)]

# MAKE SURE THE NUMBER OF BUTTONS IN THE CONFIG MATCHES THE NUMBER OF BUTTONS REPORTED BY THE ARDUINO
# If the number of buttons is not the same, deej might crash 
button_mapping:
  0:
    type: script
    value: 'c:\Users\user\Documents\Deej extra\switch-audio-output.bat'
  1:
    type: key
    value: '4274'
  2:
    type: key
    value: '4273'
  3:
    type: script
    value: 'c:\Users\user\Documents\Deej extra\turn-desk-lamp-on.bat'
  # Kept support for legacy config. requires quotes
  4: '4229'
  5: '4230'

# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# select if deej should be added to the startup apps list
run_on_startup: false

# settings for connecting to the arduino board
com_port: COM4
baud_rate: 9600

# adjust the amount of signal noise reduction depending on your hardware quality
# supported values are "low" (excellent hardware), "default" (regular hardware) or "high" (bad, noisy hardware)
noise_reduction: default
